---
title       : Lehigh University Research Computing
subtitle    : Library & Technology Services
author      : Alex Pacheco
job         : 
logo        : LURC.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : prettify      # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
--- .rcr

## About Us?

* Who?
  - Unit of Lehigh's Library & Technology Services within the Center for Innovation inTeaching & Learning

* Our Mission
  - We enable Lehigh Faculty, Researchers and Scholars achieve their goals by providing various computational resources; hardware, software, and storage; consulting and training.
  
* Research Computing Staff
  - Alex Pacheco, Manager
  - Steve Anthony, HPC User Support & System Administrator
  - Steve Lidie, System Administrator
  - Mary Jo Schulze, Software Specialist
  - Dan Brashler, Computing Consultant

---.rcr

## Research Computing Resources

* High Performance Computing (<em>free</em> and <strong>fee</strong> based)
  - <em>Maia</em>: 32-core linux cluster 
  - <strong>Corona</strong>: 1024-core linux cluster
  - <strong>Capella</strong>: 16-core linux server
  - <strong>Trits</strong>: Three 8-core linux servers
  - <strong>Cuda0</strong>: 6-core linux server with 4 nVIDIA GPUs
* High Performance Data Storage
  - <strong>Ceph</strong>: Based on Ceph, distributed object store and file 
system designed to provide excellent performance, 
reliability and scalability.
  - <em>R-Drive</em>: Ceph project that provides all full-
time faculty with 1TB of storage space.

--- .rcr 

## Services Provided

* Hardware Support
  - Provide system administration and support for Lehigh's HPC clusters.
  - Assist with purchase, installation and administration of servers and clusters for research and education.
* Software Support
  - Provide technical support for software applications, install software as requested and assist with purchase of software for research and education.
* Data Storage
  - Provide data management services including storing and sharing data. 
* Training & Consulting
  - Provide education and training programs to facilitate use of HPC resources and general scientific computing needs.
  - Provide consultation and support for code development and visualization.

--- .rcr 

## Services Provided (contd)

* Grant Support
  - Assist Faculty with proposal writing by
  <ul>
    <li>estimating cost of service and hardware acquisition,</li>
    <li>providing letter if commitment,</li>
    <li>providing documentation of the facilities, and</li>
    <li>assisting with creating a data management plan.</li>
  </ul>
* Cyberinfrastructure Support
  - Provide access to the national cyberinfrastructure backbone
  <ul>
    <li>Internet2</li>
    <li>XSEDE: Extreme Science and Engineering Discovery Environment.</li>
  </ul>

--- .rcr 

## Upcoming Training Events

* HPC resources at Lehigh
* Storage Options at Lehigh
* Introduction to Linux
* Shell Scripting
* Programming in Matlab & GNU Octave 
* Programming in R
* XSEDE HPC Monthly Workshop: Big Data

--- .rcr

## Research Computing in the Classroom

* Hello










