---
title       : Lehigh University Research Computing
subtitle    : Library & Technology Services
author      : Alex Pacheco
job         : https://researchcomputing.lehigh.edu
logo        : lu.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : prettify      # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
--- .rcr

## Research Computing Resources

* Corona
  - 40 nodes, dual 8-core AMD Opteron 6128, 2 GHz, 32GB RAM, 1TB HDD
  - 24 nodes, dual 8-core AMD Opteron 6128, 2 GHz, 64GB RAM, 2TB HDD, Infiniband QDR
  - Theoretical Performance: 8.2TFlops

* Maia
  - One node, dual 16-core AMD Opteron 6380, 2.5 GHz, 128GB RAM, 4TB HDD
  - Theoretical Performance: 640GFlops
  
* Trit
  - Three SunFire x2270 Servers each with
    -  dual 4-core Intel Xeon X5570, 2.95 GHz, 48GB RAM, 500GB HDD
  - Theoretical Performance: 283.2GFlops
  
* Capella
  - One node, quad 4-core AMD Opteron 8384, 2.7 GHz, 64GB RAM, 2x 146GB HDD
  - Theoretical Performance: 128GFlops

* Cuda0
  - One node, 6-core Intel Xeon X5650, 2.66 GHz, 24GB RAM, 200GB HDD
  - 4 nVIDIA Fermi Devices (C2050, C2070, 2x M2070)
  - Theoretical Performance: 63.840 GFlops (CPU) + 2.06 TFlops (GPU)

* Faculty Owned Clusters
  - Eight nodes, dual 8-core Intel Xeon E5-2650v2, 2.6 GHz, 64GB RAM
    - Theoretical Performance: 2.662TFlops
  - Six nodes, dual 10-core Intel Xeon E5-2650v3, 2.3GHz, 64GB RAM, nVIDIA Tesla K80, 1TB HDD
    - Theoretical Performance: 4.416 TFlops (CPU) + 17.46TFlops (GPU)

* Total Theoretical Performance: 35.9 TFlops

* Ceph
  - 1PB data storage system based on Ceph
  
--- .rcr 

## Planned Upgrade

* 64 node cluster to replace Corona, Capella, Trits and Cuda0
  - dual 10-core Intel Xeon E5-2650v3, 2.3GHz
  - 128GB RAM
  - nVIDIA Tesla K80
  - 1TB HDD
  - Fully non-blocking Infiniband EDR
  - 50TB CephFS distributed storage

--- .rcr

## HPC Training

* Provide training to Lehigh researchers
  * HPC resources at Lehigh
  * Storage Options at Lehigh
  * Introduction to Linux
  * Shell Scripting
  * Programming in Matlab & GNU Octave
  * C Programming
  * Fortran Programming
  * Programming in R
  * Satellite site for XSEDE Workshops
    - XSEDE HPC Monthly Workshop: OpenACC
    - XSEDE HPC Summer BootCamp (OpenACC, OpenMP and MPI)
    - XSEDE HPC Monthly Workshop: Big Data

--- .rcr

